export const Menus = [
  {
    label: "Men",
    image: "./men.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Men's Clothing",
        items: [
          { name: "T-shirt", slug: "search" },
          { name: "Formal Shirt", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Cargos", slug: "search" },
          { name: "Trousers", slug: "search" },
          { name: "Track Pants", slug: "search" },
          { name: "Shorts & 3/4TH", slug: "search" },
          { name: "Jackets", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Winter Wear", slug: "search" },
          { name: "Inner & Sleepwear", slug: "search" },
          { name: "29k Store", slug: "search" },
        ],
      },
      {
        title: "Sportswear",
        items: [
          { name: "Casual Shoes", slug: "search" },
          { name: "Shoe Care Kit & Accessories", slug: "search" },
          { name: "Sports Shoes", slug: "search" },
          { name: "Formal Shoes", slug: "search" },
          { name: "Sandals & Flip Flops", slug: "search" },
          { name: "Loafers & Moccasins", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Ethnic", slug: "search" },
          { name: "Speciality Footwear", slug: "search" },
          { name: "Top Selling Brands", slug: "search" },
        ],
      },
      {
        title: "Men’s Watches",
        items: [
          { name: "Watch Combos", slug: "search" },
          { name: "Couple Watches", slug: "search" },
          { name: "Fastrack, Sonata & More", slug: "search" },
          { name: "Budget Watches", slug: "search" },
        ],
      },
      {
        title: "Accessories",
        items: [
          { name: "Belts", slug: "search" },
          { name: "Wallets", slug: "search" },
          { name: "Caps & Hats", slug: "search" },
          { name: "Ties & Cufflinks", slug: "search" },
          { name: "Sunglasses", slug: "search" },
          { name: "Watches", slug: "search" },
        ],
      },
      {
        title: "Men’s Jewellery",
        items: [
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Chains & Pendants", slug: "search" },
          { name: "Precious Jewellery", slug: "search" },
          { name: "Silver Jewellery", slug: "search" },
        ],
      },
      {
        title: "Grooming",
        items: [
          { name: "Beard & Moustache Care", slug: "search" },
          { name: "Men’s Shaving", slug: "search" },
          { name: "Grooming Appliances", slug: "search" },
          { name: "Bath Essentials", slug: "search" },
          { name: "Oral Care", slug: "search" },
          { name: "Skin Care", slug: "search" },
          { name: "Hair Care", slug: "search" },
        ],
      },
      {
        title: "Eyewear",
        items: [{ name: "Sunglasses", slug: "search" }],
      },
      {
        title: "Fashion Accessories",
        items: [
          { name: "Wallets", slug: "search" },
          { name: "Belts", slug: "search" },
          { name: "Socks", slug: "search" },
          { name: "Caps", slug: "search" },
          { name: "Winter Accessories", slug: "search" },
          { name: "Winter Accessories Gift Sets", slug: "search" },
        ],
      },
      {
        title: "Bags & Luggage",
        items: [
          { name: "Backpacks & Laptop Bags", slug: "search" },
          { name: "Gym Bags", slug: "search" },
          { name: "Trolleys & Duffle Bags", slug: "search" },
          { name: "Travel Accessories", slug: "search" },
          { name: "Messenger Bags", slug: "search" },
          { name: "Rucksacks", slug: "search" },
        ],
      },
    ],
    gridCols: 4,
  },
  {
    label: "Women",
    image: "./women.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { name: "Dresses", slug: "search" },
          { name: "Tops", slug: "search" },
          { name: "T-shirts", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Trousers & Capris", slug: "search" },
          { name: "Shorts & Skirts", slug: "search" },
          { name: "Co-ords", slug: "search" },
          { name: "Playsuits", slug: "search" },
          { name: "Jumpsuits", slug: "search" },
          { name: "Shrugs", slug: "search" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { name: "Flats", slug: "search" },
          { name: "Casual Shoes", slug: "search" },
          { name: "Heels", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Sports Shoes & Floaters", slug: "search" },
        ],
      },
      {
        title: "Lingerie",
        items: [
          { name: "Bra", slug: "search" },
          { name: "Briefs", slug: "search" },
          { name: "Shapewear", slug: "search" },
          { name: "Sleepwear & Loungewear", slug: "search" },
          { name: "Swimwear", slug: "search" },
          { name: "Camisoles & Thermals", slug: "search" },
        ],
      },
      {
        title: "Active Go",
        items: [
          { name: "Sports & Active Wear", slug: "search" },
          { name: "Clothing", slug: "search" },
          { name: "Footwear", slug: "search" },
          { name: "Sports Accessories", slug: "search" },
          { name: "Sports Equipment", slug: "search" },
        ],
      },
      {
        title: "BagHub",
        items: [{ name: "GoBag", slug: "search" }],
      },
      {
        title: "Jewellery",
        items: [
          { name: "Maternity", slug: "search" },
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Fine Jewellery", slug: "search" },
          { name: "Earrings", slug: "search" },
        ],
      },
      {
        title: "Belts & Scarves",
        items: [],
      },
      {
        title: "Sunglasses",
        items: [],
      },
      {
        title: "Watches",
        items: [],
      },
    ],
    gridCols: 3,
  },
  {
    label: "Kids",
    image: "./kids.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { name: "Dresses", slug: "search" },
          { name: "Tops", slug: "search" },
          { name: "T-shirts", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Trousers & Capris", slug: "search" },
          { name: "Shorts & Skirts", slug: "search" },
          { name: "Co-ords", slug: "search" },
          { name: "Playsuits", slug: "search" },
          { name: "Jumpsuits", slug: "search" },
          { name: "Shrugs", slug: "search" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { name: "Flats", slug: "search" },
          { name: "Casual Shoes", slug: "search" },
          { name: "Heels", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Sports Shoes & Floaters", slug: "search" },
        ],
      },
      {
        title: "Lingerie",
        items: [
          { name: "Bra", slug: "search" },
          { name: "Briefs", slug: "search" },
          { name: "Shapewear", slug: "search" },
          { name: "Sleepwear & Loungewear", slug: "search" },
          { name: "Swimwear", slug: "search" },
          { name: "Camisoles & Thermals", slug: "search" },
        ],
      },
      {
        title: "Active Go",
        items: [
          { name: "Sports & Active Wear", slug: "search" },
          { name: "Clothing", slug: "search" },
          { name: "Footwear", slug: "search" },
          { name: "Sports Accessories", slug: "search" },
          { name: "Sports Equipment", slug: "search" },
        ],
      },
      {
        title: "BagHub",
        items: [{ name: "GoBag", slug: "search" }],
      },
      {
        title: "Jewellery",
        items: [
          { name: "Maternity", slug: "search" },
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Fine Jewellery", slug: "search" },
          { name: "Earrings", slug: "search" },
        ],
      },
      {
        title: "Belts & Scarves",
        items: [],
      },
      {
        title: "Sunglasses",
        items: [],
      },
      {
        title: "Watches",
        items: [],
      },
    ],
    gridCols: 3,
  },
  {
    label: "Beauty",
    image: "./beauty.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { name: "Dresses", slug: "search" },
          { name: "Tops", slug: "search" },
          { name: "T-shirts", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Trousers & Capris", slug: "search" },
          { name: "Shorts & Skirts", slug: "search" },
          { name: "Co-ords", slug: "search" },
          { name: "Playsuits", slug: "search" },
          { name: "Jumpsuits", slug: "search" },
          { name: "Shrugs", slug: "search" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { name: "Flats", slug: "search" },
          { name: "Casual Shoes", slug: "search" },
          { name: "Heels", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Sports Shoes & Floaters", slug: "search" },
        ],
      },
      {
        title: "Lingerie",
        items: [
          { name: "Bra", slug: "search" },
          { name: "Briefs", slug: "search" },
          { name: "Shapewear", slug: "search" },
          { name: "Sleepwear & Loungewear", slug: "search" },
          { name: "Swimwear", slug: "search" },
          { name: "Camisoles & Thermals", slug: "search" },
        ],
      },
      {
        title: "Active Go",
        items: [
          { name: "Sports & Active Wear", slug: "search" },
          { name: "Clothing", slug: "search" },
          { name: "Footwear", slug: "search" },
          { name: "Sports Accessories", slug: "search" },
          { name: "Sports Equipment", slug: "search" },
        ],
      },
      {
        title: "BagHub",
        items: [{ name: "GoBag", slug: "search" }],
      },
      {
        title: "Jewellery",
        items: [
          { name: "Maternity", slug: "search" },
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Fine Jewellery", slug: "search" },
          { name: "Earrings", slug: "search" },
        ],
      },
      {
        title: "Belts & Scarves",
        items: [],
      },
      {
        title: "Sunglasses",
        items: [],
      },
      {
        title: "Watches",
        items: [],
      },
    ],
    gridCols: 3,
  },
  {
    label: "Home Decor",
    image: "./home-decore.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { name: "Dresses", slug: "search" },
          { name: "Tops", slug: "search" },
          { name: "T-shirts", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Trousers & Capris", slug: "search" },
          { name: "Shorts & Skirts", slug: "search" },
          { name: "Co-ords", slug: "search" },
          { name: "Playsuits", slug: "search" },
          { name: "Jumpsuits", slug: "search" },
          { name: "Shrugs", slug: "search" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { name: "Flats", slug: "search" },
          { name: "Casual Shoes", slug: "search" },
          { name: "Heels", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Sports Shoes & Floaters", slug: "search" },
        ],
      },
      {
        title: "Lingerie",
        items: [
          { name: "Bra", slug: "search" },
          { name: "Briefs", slug: "search" },
          { name: "Shapewear", slug: "search" },
          { name: "Sleepwear & Loungewear", slug: "search" },
          { name: "Swimwear", slug: "search" },
          { name: "Camisoles & Thermals", slug: "search" },
        ],
      },
      {
        title: "Active Go",
        items: [
          { name: "Sports & Active Wear", slug: "search" },
          { name: "Clothing", slug: "search" },
          { name: "Footwear", slug: "search" },
          { name: "Sports Accessories", slug: "search" },
          { name: "Sports Equipment", slug: "search" },
        ],
      },
      {
        title: "BagHub",
        items: [{ name: "GoBag", slug: "search" }],
      },
      {
        title: "Jewellery",
        items: [
          { name: "Maternity", slug: "search" },
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Fine Jewellery", slug: "search" },
          { name: "Earrings", slug: "search" },
        ],
      },
      {
        title: "Belts & Scarves",
        items: [],
      },
      {
        title: "Sunglasses",
        items: [],
      },
      {
        title: "Watches",
        items: [],
      },
    ],
    gridCols: 3,
  },
  {
    label: "Home Appliances",
    image: "./home-appliences.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "BagHub",
        items: [{ name: "GoBag", slug: "search" }],
      },
      {
        title: "Jewellery",
        items: [
          { name: "Maternity", slug: "search" },
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Fine Jewellery", slug: "search" },
          { name: "Earrings", slug: "search" },
        ],
      },
      {
        title: "Belts & Scarves",
        items: [],
      },
      {
        title: "Sunglasses",
        items: [],
      },
    ],
    gridCols: 2,
  },
  {
    label: "Electronics",
    image: "./electronics.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [
          { name: "Kurtis, Tunics & Tops", slug: "search" },
          { name: "Sarees", slug: "search" },
          { name: "Ethnic Wear", slug: "search" },
          { name: "Leggings, Salwars & Churidars", slug: "search" },
          { name: "Skirts & Palazzos", slug: "search" },
          { name: "Dress Materials", slug: "search" },
          { name: "Lehenga Cholis", slug: "search" },
          { name: "Dupattas & Shawls", slug: "search" },
          { name: "Jackets", slug: "search" },
        ],
      },
      {
        title: "Western Wear",
        items: [
          { name: "Dresses", slug: "search" },
          { name: "Tops", slug: "search" },
          { name: "T-shirts", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Trousers & Capris", slug: "search" },
          { name: "Shorts & Skirts", slug: "search" },
          { name: "Co-ords", slug: "search" },
          { name: "Playsuits", slug: "search" },
          { name: "Jumpsuits", slug: "search" },
          { name: "Shrugs", slug: "search" },
        ],
      },
      {
        title: "Footwear",
        items: [
          { name: "Flats", slug: "search" },
          { name: "Casual Shoes", slug: "search" },
          { name: "Heels", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Sports Shoes & Floaters", slug: "search" },
        ],
      },
      {
        title: "Lingerie",
        items: [
          { name: "Bra", slug: "search" },
          { name: "Briefs", slug: "search" },
          { name: "Shapewear", slug: "search" },
          { name: "Sleepwear & Loungewear", slug: "search" },
          { name: "Swimwear", slug: "search" },
          { name: "Camisoles & Thermals", slug: "search" },
        ],
      },
    ],
    gridCols: 2,
  },
];

export const storeMenu = [
  {
    label: "Men",
    image: "./nav/men.png",
    toggleMenu: true,
    subMenu: [
      {
        title: "Men's Clothing",
        items: [
          { name: "T-shirt", slug: "search" },
          { name: "Formal Shirt", slug: "search" },
          { name: "Jeans", slug: "search" },
          { name: "Cargos", slug: "search" },
        ],
      },
      {
        title: "Sportswear",
        items: [
          { name: "Casual Shoes", slug: "search" },
          { name: "Shoe Care Kit & Accessories", slug: "search" },
          { name: "Sports Shoes", slug: "search" },
          { name: "Loafers & Moccasins", slug: "search" },
          { name: "Boots", slug: "search" },
          { name: "Ethnic", slug: "search" },
          { name: "Top Selling Brands", slug: "search" },
        ],
      },
      {
        title: "Men’s Watches",
        items: [
          { name: "Watch Combos", slug: "search" },
          { name: "Couple Watches", slug: "search" },
          { name: "Fastrack, Sonata & More", slug: "search" },
          { name: "Budget Watches", slug: "search" },
        ],
      },
      {
        title: "Men’s Jewellery",
        items: [
          { name: "Fashion Jewellery", slug: "search" },
          { name: "Precious Jewellery", slug: "search" },
          { name: "Silver Jewellery", slug: "search" },
        ],
      },
      {
        title: "Grooming",
        items: [
          { name: "Beard & Moustache Care", slug: "search" },
          { name: "Skin Care", slug: "search" },
          { name: "Hair Care", slug: "search" },
        ],
      },
      {
        title: "Eyewear",
        items: [{ name: "Sunglasses", slug: "search" }],
      },
      {
        title: "Fashion Accessories",
        items: [
          { name: "Wallets", slug: "search" },
          { name: "Socks", slug: "search" },
          { name: "Caps", slug: "search" },
          { name: "Winter Accessories", slug: "search" },
        ],
      },
      {
        title: "Bags & Luggage",
        items: [
          { name: "Backpacks & Laptop Bags", slug: "search" },
          { name: "Gym Bags", slug: "search" },
          { name: "Rucksacks", slug: "search" },
        ],
      },
    ],
    gridCols: 4,
  },
  {
    label: "Women",
    image: "./women.svg",
    toggleMenu: true,
    subMenu: [
      {
        title: "Indiwear",
        items: [{ name: "Kurtis, Tunics & Tops", slug: "search" }],
      },
    ],
    gridCols: 3,
  },
];

export const filterMenuMen = [
  {
    "Men's Clothing": [
      "T-shirt",
      "Formal Shirt",
      "Jeans",
      "Cargos",
      "Trousers",
      "Track Pants",
      "Shorts & 3/4TH",
      "Jackets",
      "Ethnic Wear",
      "Winter Wear",
      "Inner & Sleepwear",
      "29k Store",
    ],
    Sportswear: [
      "Casual Shoes",
      "Shoe Care Kit & Accessories",
      "Sports Shoes",
      "Formal Shoes",
      "Sandals & Flip Flops",
      "Loafers & Moccasins",
      "Boots",
      "Ethnic",
      "Speciality Footwear",
      "Top Selling Brands",
    ],
    "Men’s Watches": [
      "Watch Combos",
      "Couple Watches",
      "Fastrack, Sonata & More",
      "Budget Watches",
    ],
    Accessories: [
      "Belts",
      "Wallets",
      "Caps & Hats",
      "Ties & Cufflinks",
      "Sunglasses",
      "Watches",
    ],
    "Men’s Jewellery": [
      "Fashion Jewellery",
      "Chains & Pendants",
      "Precious Jewellery",
      "Silver Jewellery",
    ],
    Grooming: [
      "Beard & Moustache Care",
      "Men’s Shaving",
      "Grooming Appliances",
      "Bath Essentials",
      "Oral Care",
      "Skin Care",
      "Hair Care",
    ],
    Eyewear: ["Sunglasses"],
    "Fashion Accessories": [
      "Wallets",
      "Belts",
      "Socks",
      "Caps",
      "Winter Accessories",
      "Winter Accessories Gift Sets",
    ],
    "Bags & Luggage": [
      "Backpacks & Laptop Bags",
      "Gym Bags",
      "Trolleys & Duffle Bags",
      "Travel Accessories",
      "Messenger Bags",
      "Rucksacks",
    ],
  },
];
